GET http://localhost:5191/WeatherForecast
Authorization : Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE2ODcyNjA2ODEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSJ9.QY5SIhWS7KhwRuaQ4Rf43pjqP2gfPj2hQi6GoyEzlwM






POST http://localhost:5191/Account/Logout
Authorization : Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE2ODcyNjA2ODEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSJ9.QY5SIhWS7KhwRuaQ4Rf43pjqP2gfPj2hQi6GoyEzlwM





POST http://localhost:5191/Account/Refresh
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE2ODcyNjA4MzcsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5MSJ9.x_QJVYmMh74Q23yrLbqfW4041wWdiIf5IWUVMUtxosA

{
	"RefreshToken" : "wJF4Euue773YtjQD8NkZFV3zvUASg4/ht7bDLlSgVRA="
}